# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Squashed initial migration — full final schema, no data operations.
# Generated by Django 6.0.7 on 2026-07-12

import uuid

import django.db.models.deletion
from django.db import migrations, models

import django_returns.models.return_attachment


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_returns", "0001_initial"),
        ("django_returns", "0002_orderreturn_return_attachment_and_more"),
    ]

    dependencies = [
        ("django_accounts", "0001_squashed_0032_customer_indexes"),
        ("django_checkout", "0001_squashed_0083_remove_paymentintent_one_intent_per_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(default="", max_length=128, unique=True)),
                ("return_methods", models.JSONField(blank=True, null=True)),
                ("return_solutions", models.JSONField(blank=True, null=True)),
                ("logo_on_document", models.ImageField(blank=True, null=True, upload_to="pic")),
                ("shop_shipping_address", models.TextField(blank=True, max_length=1024, null=True)),
                ("email_administrator", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name_plural": "Returns - channels",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="OrderReturn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=256),
                ),
                ("return_method", models.CharField(blank=True, max_length=256, null=True)),
                ("return_solution", models.CharField(blank=True, max_length=256, null=True)),
                ("comment", models.TextField(blank=True, max_length=300, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("bank_account_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns_customer",
                        to="django_accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns_order",
                        to="django_checkout.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderReturnProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "order_return",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_returns.orderreturn"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_checkout.productrepresentation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="orderreturn",
            name="products",
            field=models.ManyToManyField(
                related_name="order_return_products",
                through="django_returns.OrderReturnProduct",
                to="django_checkout.productrepresentation",
            ),
        ),
        migrations.CreateModel(
            name="ReturnAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="It will automatically be filled in with the file name when saving",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        storage=django_returns.models.return_attachment.order_storage,
                        upload_to=django_returns.models.return_attachment.order_directory_path,
                    ),
                ),
                (
                    "order_return",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="django_returns.orderreturn"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="orderreturn",
            name="return_attachment",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="django_returns.returnattachment"
            ),
        ),
    ]
